# 数据源
spring:
  application:
    name: xy-data
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# swagger-ui
swagger:
  enable: true

# log
logging:
  level:
    com.xy: DEBUG
  # 默认日志路径
  path: ..
  file: ./xy-log/xy-data.log